import sqlite3
from pathlib import Path

DB = str(Path(__file__).resolve().parents[1] / "backend" / "hanbando.db")

SEEDS = [
    # ── 토종 14종 ──────────────────────────────────────────────────
    {
        "korean_name": "구상나무",
        "scientific_name": "Abies koreana",
        "native_status": "토종",
        "confidence": 0.96,
        "ecology_summary": "한국 고유종 침엽수로 해발 1,000m 이상 고산지대에 자생. 기후변화로 서식지가 급격히 줄어 국제적 멸종위기종으로 지정됨.",
        "conservation_status": "EN",
        "morphological_clues": "잎 뒷면에 흰색 기공선이 두 줄, 구과는 자주빛 원통형, 성숙하면 녹색→자주→갈색 변화",
        "image_path": "/assets/illustrations/plant_009_구상나무.png",
        "memo": "한라산 정상부 군락",
        "lat": 33.3617, "lng": 126.5292, "district": "제주 한라산",
        "created_at": "2026-05-14 09:12:33",
    },
    {
        "korean_name": "미선나무",
        "scientific_name": "Abeliophyllum distichum",
        "native_status": "토종",
        "confidence": 0.93,
        "ecology_summary": "한국에서만 자라는 1속 1종의 한국 특산식물. 이른 봄 흰 꽃이 피며 선형 시과가 특징. 천연기념물이자 멸종위기 2급.",
        "conservation_status": "VU",
        "morphological_clues": "부채꼴 납작한 시과, 2월~3월 잎보다 먼저 흰 꽃 개화, 대생 타원형 잎",
        "image_path": "/assets/illustrations/plant_030_미선나무.png",
        "memo": "괴산 미선나무 자생지",
        "lat": 36.8872, "lng": 127.8067, "district": "충북 괴산",
        "created_at": "2026-05-13 14:22:05",
    },
    {
        "korean_name": "금강초롱꽃",
        "scientific_name": "Hanabusaya asiatica",
        "native_status": "토종",
        "confidence": 0.91,
        "ecology_summary": "한국 특산 초롱꽃과 식물. 금강산·설악산 등 고산 암벽에 자생하며 보라색 종형 꽃이 특징. 속명은 일제강점기 외교관 이름에서 유래.",
        "conservation_status": "LC",
        "morphological_clues": "보라색 종 모양 꽃, 잎은 심장형 거치, 높이 40~80cm, 8~9월 개화",
        "image_path": "/assets/illustrations/plant_010_금강초롱꽃.png",
        "memo": "설악산 천불동계곡 암벽",
        "lat": 38.1195, "lng": 128.4656, "district": "강원 인제",
        "created_at": "2026-05-12 11:05:47",
    },
    {
        "korean_name": "동강할미꽃",
        "scientific_name": "Pulsatilla tongkangensis",
        "native_status": "토종",
        "confidence": 0.89,
        "ecology_summary": "동강 석회암 절벽에만 자생하는 한국 특산종. 할미꽃보다 꽃잎이 더 크고 보라색. 서식지 특이성으로 개체수가 매우 제한적.",
        "conservation_status": "EN",
        "morphological_clues": "꽃잎 6장 보라색, 석회암 절벽 틈 자생, 3~4월 개화, 전체 흰 솜털",
        "image_path": "/assets/illustrations/plant_024_동강할미꽃.png",
        "memo": "동강 백운산 절벽",
        "lat": 37.2048, "lng": 128.5773, "district": "강원 영월",
        "created_at": "2026-05-10 08:34:21",
    },
    {
        "korean_name": "노랑붓꽃",
        "scientific_name": "Iris koreana",
        "native_status": "토종",
        "confidence": 0.94,
        "ecology_summary": "한국 특산 붓꽃. 황색 꽃이 피며 전라도 일부 지역에만 분포. 자생지가 극히 제한적으로 멸종위기 식물로 보호 중.",
        "conservation_status": "EN",
        "morphological_clues": "노란색 외화피 3장, 5월 개화, 잎은 선형 직립, 키 20~40cm",
        "image_path": "/assets/illustrations/plant_017_노랑붓꽃.png",
        "memo": "지리산 계곡부 습지",
        "lat": 35.3370, "lng": 127.7306, "district": "전남 구례",
        "created_at": "2026-05-11 15:48:09",
    },
    {
        "korean_name": "개느삼",
        "scientific_name": "Echinosophora koreensis",
        "native_status": "토종",
        "confidence": 0.88,
        "ecology_summary": "한국 특산 콩과 식물. 경기·강원 일부 석회암 지대에 자생. 가시 모양 탁엽과 황색 꽃이 특징. 환경부 멸종위기 1급.",
        "conservation_status": "CR",
        "morphological_clues": "가시 같은 탁엽, 황색 나비형 꽃, 홀수우상복엽, 5~6월 개화",
        "image_path": "/assets/illustrations/plant_005_개느삼.png",
        "memo": "영월 석회암 지대 군락 발견",
        "lat": 37.1836, "lng": 128.4614, "district": "강원 영월",
        "created_at": "2026-05-09 10:22:44",
    },
    {
        "korean_name": "고려엉겅퀴",
        "scientific_name": "Cirsium setidens",
        "native_status": "토종",
        "confidence": 0.87,
        "ecology_summary": "한국 특산 엉겅퀴로 곤드레나물의 식재료 원형. 강원도 산지 초원에 자생. 자주색 두상화, 잎에 가시 발달.",
        "conservation_status": "LC",
        "morphological_clues": "두상화 자주색, 잎 가시 발달, 높이 1m 내외, 8~10월 개화",
        "image_path": "/assets/illustrations/plant_008_고려엉겅퀴.png",
        "memo": "평창 산지 초원 대규모 군락",
        "lat": 37.3707, "lng": 128.4935, "district": "강원 평창",
        "created_at": "2026-05-08 13:15:30",
    },
    {
        "korean_name": "곰취",
        "scientific_name": "Ligularia fischeri",
        "native_status": "토종",
        "confidence": 0.92,
        "ecology_summary": "산지 습한 곳에 자생하는 국화과 여러해살이풀. 봄철 어린잎은 쌉싸름한 나물로 애용. 노란 두상화가 총상으로 달림.",
        "conservation_status": "LC",
        "morphological_clues": "잎 신장형 대형(지름 30cm 이상), 노란 설상화, 높이 1~2m, 8~9월 개화",
        "image_path": "/assets/illustrations/plant_007_곰취.png",
        "memo": "오대산 습한 계곡 사면",
        "lat": 37.7991, "lng": 128.5425, "district": "강원 평창",
        "created_at": "2026-05-07 09:55:17",
    },
    {
        "korean_name": "노랑무늬붓꽃",
        "scientific_name": "Iris odaesanensis",
        "native_status": "토종",
        "confidence": 0.85,
        "ecology_summary": "오대산 일대 자생 한국 특산 붓꽃. 흰 꽃잎에 노란 줄무늬가 특징. 고산 반음지 숲 가장자리에 군락.",
        "conservation_status": "VU",
        "morphological_clues": "흰색 외화피에 노란 줄무늬, 5~6월 개화, 잎 선형",
        "image_path": "/assets/illustrations/plant_016_노랑무늬붓꽃.png",
        "memo": "오대산 월정사 주변 군락",
        "lat": 37.7441, "lng": 128.5367, "district": "강원 평창",
        "created_at": "2026-05-06 16:30:58",
    },
    {
        "korean_name": "금꿩의다리",
        "scientific_name": "Thalictrum rochebrunianum",
        "native_status": "토종",
        "confidence": 0.83,
        "ecology_summary": "한국 특산 미나리아재비과 식물. 산지 숲 속 습윤한 곳에 자생. 황색 수술이 드리워지는 꽃이 특징.",
        "conservation_status": "LC",
        "morphological_clues": "황색 수술 다수 드리움, 2~3회 우상복엽, 높이 1~1.5m, 7~8월 개화",
        "image_path": "/assets/illustrations/plant_011_금꿩의다리.png",
        "memo": "속리산 습한 계곡",
        "lat": 36.5395, "lng": 127.8640, "district": "충북 보은",
        "created_at": "2026-05-05 11:20:03",
    },
    {
        "korean_name": "개족도리풀",
        "scientific_name": "Asarum maculatum",
        "native_status": "토종",
        "confidence": 0.86,
        "ecology_summary": "한국 특산 쥐방울덩굴과 식물. 잎에 흰 무늬가 있어 관상 가치가 높으며 숲 속 음지에 자생.",
        "conservation_status": "LC",
        "morphological_clues": "잎 심장형 흰 무늬 산재, 꽃은 땅 가까이 자주색 항아리형, 상록성",
        "image_path": "/assets/illustrations/plant_006_개족도리풀.png",
        "memo": "지리산 노고단 숲 하부",
        "lat": 35.3565, "lng": 127.6024, "district": "전남 구례",
        "created_at": "2026-05-04 14:44:11",
    },
    {
        "korean_name": "좀민들레",
        "scientific_name": "Taraxacum hallaisanense",
        "native_status": "토종",
        "confidence": 0.90,
        "ecology_summary": "제주 한라산 고지대에 자생하는 토종 민들레. 서양민들레와 달리 총포 외편이 뒤로 젖혀지지 않음. 군락이 급감 중.",
        "conservation_status": "VU",
        "morphological_clues": "총포 외편 직립(서양민들레는 반곡), 꽃 노란색, 봄 개화",
        "image_path": "/assets/illustrations/plant_074_좀민들레.png",
        "memo": "한라산 1,400m 이상 초원",
        "lat": 33.3820, "lng": 126.5312, "district": "제주 한라산",
        "created_at": "2026-05-03 08:10:45",
    },
    {
        "korean_name": "가시딸기",
        "scientific_name": "Rubus hongnoensis",
        "native_status": "토종",
        "confidence": 0.84,
        "ecology_summary": "제주도 및 남해 도서 자생 한국 특산 장미과 식물. 줄기에 가시가 밀생하며 흰 꽃이 피고 붉은 복분자 형태 열매 결실.",
        "conservation_status": "LC",
        "morphological_clues": "줄기 가시 밀생, 잎 3~5갈래, 흰 꽃 5판, 붉은 취합과",
        "image_path": "/assets/illustrations/plant_001_가시딸기.png",
        "memo": "제주 한라산 중산간 덤불",
        "lat": 33.4071, "lng": 126.6231, "district": "제주",
        "created_at": "2026-05-02 13:27:39",
    },
    {
        "korean_name": "나도승마",
        "scientific_name": "Kirengeshoma koreana",
        "native_status": "토종",
        "confidence": 0.88,
        "ecology_summary": "한국 특산 범의귀과 식물. 지리산 등 남부 고산 숲 속에 자생. 노란 꽃이 종형으로 드리우며 잎이 단풍잎처럼 갈라짐.",
        "conservation_status": "EN",
        "morphological_clues": "잎 손바닥형 7~9갈래, 노란 종형 꽃, 높이 60~120cm, 8~9월 개화",
        "image_path": "/assets/illustrations/plant_012_나도승마.png",
        "memo": "지리산 세석평전 주변",
        "lat": 35.3143, "lng": 127.7341, "district": "경남 함양",
        "created_at": "2026-05-01 10:05:22",
    },
    # ── 외래종 5종 ──────────────────────────────────────────────────
    {
        "korean_name": "돼지풀",
        "scientific_name": "Ambrosia artemisiifolia",
        "native_status": "외래종",
        "confidence": 0.95,
        "ecology_summary": "북미 원산 환경부 지정 생태계교란 외래식물. 꽃가루가 알레르기성 비염과 천식의 주요 원인. 하천변·도로변에 급속 확산.",
        "conservation_status": "LC",
        "morphological_clues": "잎 쑥과 유사하게 깊이 갈라짐, 수꽃 이삭 황록색 늘어짐, 7~10월 개화",
        "image_path": "/assets/illustrations/plant_104_돼지풀.png",
        "memo": "한강 하천변 대규모 군락",
        "lat": 37.5520, "lng": 126.8342, "district": "서울 강서",
        "created_at": "2026-05-14 16:45:22",
    },
    {
        "korean_name": "단풍잎돼지풀",
        "scientific_name": "Ambrosia trifida",
        "native_status": "외래종",
        "confidence": 0.93,
        "ecology_summary": "돼지풀보다 키가 2~3m로 훨씬 크며 환경부 지정 생태계교란종. 잎이 단풍잎처럼 3~5갈래로 갈라져 구별. 하천변 집중 분포.",
        "conservation_status": "LC",
        "morphological_clues": "잎 3~5갈래 손바닥형, 키 2~3m 대형, 줄기 거칠고 털 밀생",
        "image_path": "/assets/illustrations/plant_103_단풍잎돼지풀.png",
        "memo": "낙동강 하천부지",
        "lat": 35.8714, "lng": 128.5997, "district": "대구 달성",
        "created_at": "2026-05-13 11:20:15",
    },
    {
        "korean_name": "미국쑥부쟁이",
        "scientific_name": "Aster pilosus",
        "native_status": "외래종",
        "confidence": 0.91,
        "ecology_summary": "북미 원산 환경부 지정 생태계교란 외래식물. 흰색 두상화가 가을에 무리 지어 피며 도로변·하천변에 넓게 퍼짐.",
        "conservation_status": "LC",
        "morphological_clues": "흰색 설상화 다수, 줄기 털 밀생, 잎 선형, 9~11월 개화",
        "image_path": "/assets/illustrations/plant_105_미국쑥부쟁이.png",
        "memo": "금강 하천변 침입 확인",
        "lat": 36.4800, "lng": 127.2892, "district": "충남 공주",
        "created_at": "2026-05-12 14:55:40",
    },
    {
        "korean_name": "양미역취",
        "scientific_name": "Solidago altissima",
        "native_status": "외래종",
        "confidence": 0.92,
        "ecology_summary": "북미 원산 생태계교란 외래식물. 가을철 노란 꽃이 대규모로 피며 토종 식물 군락을 빠르게 잠식. 뿌리에서 타감물질 분비.",
        "conservation_status": "LC",
        "morphological_clues": "황색 두상화 원추화서, 높이 1~2m, 잎 피침형 3맥 뚜렷, 9~10월 개화",
        "image_path": "/assets/illustrations/plant_106_양미역취.png",
        "memo": "북한산 등산로 입구 군락",
        "lat": 37.6587, "lng": 126.9770, "district": "서울 은평",
        "created_at": "2026-05-11 09:15:55",
    },
    {
        "korean_name": "가시박",
        "scientific_name": "Sicyos angulatus",
        "native_status": "외래종",
        "confidence": 0.94,
        "ecology_summary": "북미 원산 박과 덩굴식물. 하천변 교목을 완전히 덮어 고사시키는 생태계교란종. 가시 달린 열매 다발이 특징.",
        "conservation_status": "LC",
        "morphological_clues": "잎 손바닥형 5갈래, 열매 가시 달린 타원형 다발, 덩굴 5~10m 성장",
        "image_path": "/assets/illustrations/plant_102_가시박.png",
        "memo": "남한강 하천림 피해 심각",
        "lat": 37.4146, "lng": 127.5949, "district": "경기 양평",
        "created_at": "2026-05-10 12:40:18",
    },
]

conn = sqlite3.connect(DB)
cur = conn.cursor()

inserted = 0
for s in SEEDS:
    cur.execute("""
        INSERT INTO collection
            (korean_name, scientific_name, native_status, confidence,
             ecology_summary, conservation_status, morphological_clues,
             image_path, memo, lat, lng, district, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        s["korean_name"], s["scientific_name"], s["native_status"],
        s["confidence"], s["ecology_summary"], s["conservation_status"],
        s["morphological_clues"], s["image_path"], s["memo"],
        s["lat"], s["lng"], s["district"], s["created_at"],
    ))
    inserted += 1

conn.commit()
conn.close()
print(f"inserted {inserted}")
